# Generated by Django 4.2.7 on 2023-12-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_usuario_avaliacao_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app.cliente')),
                ('produtos', models.ManyToManyField(related_name='compra_produto', to='app.produto')),
            ],
        ),
    ]
