# Generated by Django 4.2.7 on 2023-12-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cliente_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='forncedor_user',
            new_name='fornecedor_user',
        ),
    ]
