# Generated by Django 4.2.7 on 2023-12-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_forncedor_user_fornecedor_fornecedor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
