# Generated by Django 4.2.7 on 2023-12-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(),
        ),
    ]
