# Generated by Django 4.2.7 on 2023-12-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_categoria_relatoriopesquisas_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
