# Generated by Django 4.2.7 on 2023-12-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio',
        ),
        migrations.DeleteModel(
            name='RelatorioPesquisas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
