# Generated by Django 4.2.7 on 2023-12-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_relatorio_delete_relatoriopesquisas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='app/imagens'),
            preserve_default=False,
        ),
    ]
